version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo Installing dependencies
      - apt-get update -y
      - apt-get install -y python3-venv
  pre_build:
    commands:
      - echo Setting up virtual environment
      - python3 -m venv /home/ubuntu/flaskapp/venv
      - source /home/ubuntu/flaskapp/venv/bin/activate
      - pip install -r requirements.txt
  build:
    commands:
      - echo Creating AMI
      - INSTANCE_ID=$(curl http://169.254.169.254/latest/meta-data/instance-id)
      - AMI_ID=$(aws ec2 create-image --instance-id $INSTANCE_ID --name "flask-ami-$(date +%Y-%m-%d-%H-%M)" --no-reboot --output text)
      - echo "New AMI ID: $AMI_ID"
  post_build:
    commands:
      - echo Updating launch template
      - aws ec2 create-launch-template-version --launch-template-id lt-0430b5d140e6fc111 --source-version 1 --launch-template-data "{\"ImageId\":\"$AMI_ID\"}"
      - aws autoscaling update-auto-scaling-group --auto-scaling-group-name my-project-asg --launch-template \"LaunchTemplateId=lt-0430b5d140e6fc111,Version=\$Latest\"
artifacts:
  files:
    - '**/*'
